import random
from datetime import datetime, timedelta
from fastapi import APIRouter, Depends
from typing import List, Dict
from sqlalchemy.orm import Session
from app.api.deps import get_current_active_user, get_db
from app.models.user import User
from app.models.cloud_account import CloudAccount

from app.api.pricing_service import PricingService

import logging
logger = logging.getLogger(__name__)

from app.services.budget_service import budget_service
from pydantic import BaseModel
from app.api.deps_rbac import get_current_viewer, get_current_operator

router = APIRouter(prefix="/billing", tags=["billing"])

@router.get("/compare-compute")
def compare_compute_prices(current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Fetch and compare compute rates across AWS, Azure, and GCP."""
    # Tactical Boundary Check
    if current_user.project_id:
        accounts = db.query(CloudAccount).filter(CloudAccount.project_id == current_user.project_id).all()
    else:
        accounts = db.query(CloudAccount).filter(CloudAccount.user_id == current_user.id).all()
    pricing = PricingService(db)
    return pricing.compare_compute_rates(accounts)

@router.get("/summary")
def get_billing_summary(current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Fetch aggregated billing overview. Returns mock data if actual APIs are not linked."""
    # Tactical Boundary Check
    if current_user.project_id:
        accounts = db.query(CloudAccount).filter(CloudAccount.project_id == current_user.project_id).all()
    else:
        accounts = db.query(CloudAccount).filter(CloudAccount.user_id == current_user.id).all()
    
    if not accounts:
        return {"total_cost": 0.0, "currency": "USD", "providers": {}}
    
    
    providers_cost = {}
    total = 0.0
    services_breakdown = {}
    main_account_id = None
    
    from app.api.adapters import get_adapter

    for acc in accounts:
        adapter = get_adapter(acc.provider)
        if not adapter:
            logger.warning(f"No adapter found for provider {acc.provider}")
            continue
            
        try:
            cost = adapter.get_monthly_spend(acc)
            providers_cost[acc.provider] = providers_cost.get(acc.provider, 0.0) + cost
            total += cost
            
            # Universal service breakdown via adapter
            breakdown = adapter.get_billing_breakdown(acc)
            for service, amount in breakdown.items():
                label = f"[{acc.provider.upper()}] {service}"
                services_breakdown[label] = services_breakdown.get(label, 0.0) + amount
                
        except Exception as e:
            logger.error(f"Failed to fetch live billing for {acc.provider} account {acc.id}: {e}")
            
    from app.services.optimization_service import optimization_service
    savings = optimization_service.get_total_potential_savings(db, current_user.id, current_user.project_id)
    
    linked_accounts = len(accounts)
    account_ids = [acc.id for acc in accounts]
    from app.models.resource import Resource
    active_resources = db.query(Resource).filter(Resource.cloud_account_id.in_(account_ids)).count()
    main_account_id = accounts[0].id if accounts else None

    return {
        "total_cost": round(total, 2),
        "currency": "USD",
        "providers": providers_cost,
        "services": services_breakdown,
        "account_id": main_account_id,
        "linked_accounts": linked_accounts,
        "active_resources": active_resources,
        "potential_savings": round(savings, 2)
    }

@router.get("/recommendations")
def get_optimization_recommendations(current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Fetch actionable cost-saving recommendations generated by the UniOS Optimization AI."""
    from app.services.optimization_service import optimization_service
    return optimization_service.get_savings_recommendations(db, current_user.id, current_user.project_id)

@router.get("/debug")
def debug_aws_billing(current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Diagnostic endpoint to see the real error from AWS Cost Explorer."""
    # Tactical Boundary Check
    if current_user.project_id:
        accounts = db.query(CloudAccount).filter(CloudAccount.project_id == current_user.project_id).all()
    else:
        accounts = db.query(CloudAccount).filter(CloudAccount.user_id == current_user.id).all()
    if not accounts:
        return {"status": "error", "message": "No cloud accounts linked"}
    
    results = {}
    from app.api.adapters import get_adapter
    for acc in accounts:
        if acc.provider == 'aws':
            try:
                adapter = get_adapter("aws")
                billing = adapter.get_billing_summary(acc)
                results[acc.id] = {"status": "success", "data": billing}
            except Exception as e:
                results[acc.id] = {"status": "error", "exception": str(e)}
        else:
            results[acc.id] = {"status": "skipped", "reason": "Not an AWS account"}
            
    return results

@router.get("/trends")
def get_billing_trends(days: int = 7, current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Fetch daily cost trend aggregated across ALL cloud providers."""
    # Tactical Boundary Check
    if current_user.project_id:
        accounts = db.query(CloudAccount).filter(CloudAccount.project_id == current_user.project_id).all()
    else:
        accounts = db.query(CloudAccount).filter(CloudAccount.user_id == current_user.id).all()
    if not accounts:
        return []

    from app.api.adapters import get_adapter
    
    # Combined map of Date -> {provider: cost}
    master_trends = {}
    active_providers = set()
    
    for acc in accounts:
        adapter = get_adapter(acc.provider)
        if not adapter: continue
        active_providers.add(acc.provider)
        
        try:
            # Each adapter returns list of {'date': '...', 'provider_id': cost}
            provider_trends = adapter.get_daily_costs(days=days, account=acc)
            for entry in provider_trends:
                dt = entry['date']
                if dt not in master_trends:
                    master_trends[dt] = {"date": dt}
                
                # Accumulate cost for this provider
                cost_key = acc.provider
                cost_val = entry.get(cost_key, 0)
                master_trends[dt][cost_key] = master_trends[dt].get(cost_key, 0) + cost_val
        except Exception as e:
            logger.error(f"Failed to fetch trends for {acc.provider} ({acc.id}): {e}")

    # Sorting and formatting
    result = list(master_trends.values())
    result.sort(key=lambda x: x['date'])
    
    for item in result:
        try:
            # Standardize date format for UI (MMM DD)
            d = datetime.strptime(item['date'], '%Y-%m-%d')
            item['date'] = d.strftime('%b %d')
        except:
            pass
            
    # 🔮 Synthetic Safety: Fill missing providers with 0 to ensure Recharts stability
    for item in result:
        for p in active_providers:
            if p not in item:
                item[p] = 0.0

    return result
@router.get("/history")
def get_monthly_history(months: int = 6, current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    """Fetch monthly cost history aggregated across ALL cloud providers."""
    # Tactical Boundary Check
    if current_user.project_id:
        accounts = db.query(CloudAccount).filter(CloudAccount.project_id == current_user.project_id).all()
    else:
        accounts = db.query(CloudAccount).filter(CloudAccount.user_id == current_user.id).all()
    if not accounts:
        return []

    from app.api.adapters import get_adapter
    
    master_history = {}
    active_providers = set()
    
    for acc in accounts:
        adapter = get_adapter(acc.provider)
        if not adapter: continue
        active_providers.add(acc.provider)
        
        try:
            provider_history = adapter.get_monthly_costs(months=months, account=acc)
            for entry in provider_history:
                m = entry['month']
                if m not in master_history:
                    master_history[m] = {"month": m}
                
                cost_key = acc.provider
                cost_val = entry.get(cost_key, 0)
                master_history[m][cost_key] = master_history[m].get(cost_key, 0) + cost_val
        except Exception as e:
            logger.error(f"Failed to fetch history for {acc.provider} ({acc.id}): {e}")

    result = list(master_history.values())
    result.sort(key=lambda x: x['month'])
    
    # 🔮 Format for UI (e.g. "Oct 2025")
    for item in result:
        try:
            d = datetime.strptime(item['month'], '%Y-%m')
            item['month'] = d.strftime('%b %Y')
        except:
            pass
            
    for item in result:
        for p in active_providers:
            if p not in item:
                item[p] = 0.0

    return result

@router.get("/budgets")
def get_mission_budgets(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_viewer)
):
    """Assess the current cost trajectory vs tactical budget thresholds."""
    return budget_service.check_budgets(db, current_user.id)

class BudgetUpdate(BaseModel):
    account_id: int
    limit: float
    kill_switch: bool

@router.post("/budgets/configure")
def configure_budget(
    request: BudgetUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_operator)
):
    """Update high-priority budget thresholds and enable/disable kill-switch containment."""
    return budget_service.set_budget(request.account_id, request.limit, request.kill_switch)
